version: '3'

services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_user
      MONGO_INITDB_ROOT_PASSWORD: dev_password
    volumes:
      - mongodb-data:/data/db


volumes:
  mongodb-data:
